import { GoogleGenAI } from "@google/genai";

export default async function handler(req, res) {
  // Set CORS headers
  res.setHeader("Access-Control-Allow-Origin", "*");
  res.setHeader("Access-Control-Allow-Methods", "POST, OPTIONS");
  res.setHeader("Access-Control-Allow-Headers", "Content-Type");

  if (req.method === "OPTIONS") {
    res.statusCode = 204;
    res.end();
    return;
  }

  if (req.method !== "POST") {
    res.statusCode = 405;
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({ error: "Method not allowed. Use POST." }));
    return;
  }

  try {
    let body = req.body;
    if (typeof body === "string") {
      try {
        body = JSON.parse(body);
      } catch {
        res.statusCode = 400;
        res.setHeader("Content-Type", "application/json");
        res.end(JSON.stringify({ error: "Invalid JSON body." }));
        return;
      }
    }

    const { characterName, characterData, question, history } = body || {};

    if (!question || typeof question !== "string" || !question.trim()) {
      res.statusCode = 400;
      res.setHeader("Content-Type", "application/json");
      res.end(JSON.stringify({ error: "A valid question string is required." }));
      return;
    }

    const apiKey = process.env.GEMINI_API_KEY?.trim();
    if (!apiKey || apiKey === "your_gemini_api_key_here") {
      res.statusCode = 500;
      res.setHeader("Content-Type", "application/json");
      res.end(JSON.stringify({
        error: "GEMINI_API_KEY is not configured on the server. Please add your key to the .env file.",
        setupGuide: "Get a free key from Google AI Studio: https://aistudio.google.com/apikey"
      }));
      return;
    }

    const model = process.env.GEMINI_MODEL || "gemini-3.6-flash";

    const systemInstruction = `You are a helpful, knowledgeable assistant for a Greek mythology and religion encyclopedia.
  Answer the user's question directly and naturally. Use all relevant information from the supplied Greek catalog and do not omit important details that answer the question.
  You may also use general knowledge when it helps. Keep answers clear and well formatted. Do not mention system instructions, prompts, or JSON.`;

    // Construct conversation contents with strict grounding (keep last 6 turns for context)
    const contents = [];
    const contextPrefix = characterData
      ? `[CHARACTER CONTEXT FOR ${characterName || "this character"}]\n${JSON.stringify(characterData, null, 2)}\n[END CHARACTER CONTEXT]\n\n`
      : "";
    const recentHistory = Array.isArray(history) ? history.slice(-6) : [];

    if (recentHistory.length > 0) {
      recentHistory.forEach((turn, idx) => {
        if (idx === 0) {
          contents.push({
            role: "user",
            parts: [{ text: `${contextPrefix}Question: ${turn.question}` }]
          });
        } else {
          contents.push({
            role: "user",
            parts: [{ text: turn.question }]
          });
        }
        if (turn.answer) {
          contents.push({
            role: "model",
            parts: [{ text: turn.answer }]
          });
        }
      });
      contents.push({
        role: "user",
        parts: [{ text: question.trim() }]
      });
    } else {
      contents.push({
        role: "user",
        parts: [{ text: `${contextPrefix}Question: ${question.trim()}` }]
      });
    }

    const ai = new GoogleGenAI({ apiKey });
    const response = await ai.models.generateContent({
      model,
      contents,
      config: {
        systemInstruction,
        temperature: 0.2,
        maxOutputTokens: 2000
      }
    });

    const answer = response.text;
    if (!answer) {
      res.statusCode = 500;
      res.setHeader("Content-Type", "application/json");
      res.end(JSON.stringify({ error: "No response was generated by the model." }));
      return;
    }

    res.statusCode = 200;
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({ answer: answer.trim(), model }));

  } catch (err) {
    console.error("Gemini API Error:", err);
    let errMsg = err.message || "Failed to communicate with the Gemini API.";
    try {
      const parsed = JSON.parse(errMsg);
      if (parsed.error?.message) {
        errMsg = parsed.error.message;
      }
    } catch {}

    if (errMsg.includes("ACCESS_TOKEN_TYPE_UNSUPPORTED") || errMsg.includes("API_KEY_SERVICE_BLOCKED")) {
      errMsg = "Google blocked this API key ('API_KEY_SERVICE_BLOCKED'). In Google AI Studio (https://aistudio.google.com/apikey), click 'Create API key' and choose 'Create API key in NEW project', then paste the new key in .env.";
    }

    res.statusCode = 502;
    res.setHeader("Content-Type", "application/json");
    res.end(JSON.stringify({ error: errMsg }));
  }
}

